### ISSUE TITLE
Add map marker class in webapp, replace DCSUnit class

### ISSUE THREAD

**Issue by birgersp** [birgersp/dcs-bajas#12]
Since the webapp should not process raw unit data, the DCSUnit class in [`dcs-mission-intel/webserver/public/dcsunit.js`](https://github.com/birgersp/dcs-mission-intel/blob/master/webserver/public/dcsunit.js) should be replaced with a map marker class.

**Comment by jkhoel** [comment]
This whole function has been rewritten. mint now takes a JSON stream from the server app
