### ISSUE TITLE
Name of unit in black dont show

### ISSUE THREAD

**Issue by 132ndNeck** [birgersp/dcs-bajas#39]
When looking at the map, on the units there now, there are a name and a unit size, however, this does not show well against the black map, so maybe it would be possible to change it, or make it more visible?

**Comment by jkhoel** [comment]
They are supposed to be white. It is a bug that I haven't gotten around to fixing just yet :)

**Comment by jkhoel** [comment]
Markers are now mono-color using lines only - no fills. Color is either:
* Yellow (Unknowns)
* Blue (Blue Faction)
* Red (Red Faction)
