### ISSUE TITLE
DCS unit data messages is missing comma symbol

### ISSUE THREAD

**Issue by jkhoel** [birgersp/dcs-bajas#49]
mint.lua has a bug so that it doesn't handle multiple same-coalition units. I think there is a bug where a "," is missing in-between the objects, but I couldn't see where (Lue.. I don't know it)

one red and one blue is no problem

**Comment by birgersp** [comment]
What is it causing / where does the error occur?

**Comment by birgersp** [comment]
JSON parsing error occured

```
{"red":[["IL-78M",-275285.84375,6092.0771484375,878428.625]],"blue":[["Ka-50",-206070.5625,11.540177345276,552728.875]["E-3A",-370142.71875,
6092.2387695313,675571.4375]]}
                                                                                                                      ^

SyntaxError: Unexpected token [ in JSON at position 118
```

* Add missing comma symbol to DCS data messages
